name: Push commit
on:
  project:
    types: [created]

jobs:
  rename:
    name: Rename template files with new repository name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rename files
        run: |
          sed -i.bak "s/template-react-vite/${{ github.event.repository.name }}/g" README.md
          sed -i.bak "s/template-react-vite/${{ github.event.repository.name }}/g" package.json
      - name: Commit changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "Rename template files with new project name"
          git push